# Configurations
title: analogicus
author:
  name: Carsten Wulff
  email: carsten@wulff.no
longtitle:        analogicus
description: >- # this means to ignore newlines until "baseurl:"
    I'd love to simplify analog integrated circuit design.
domain: "analogicus.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://analogicus.com" # the base hostname & protocol for your site, e.g. http://example.com

version:          1.0
gitbook_version:  3.2.3

rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: wulffern/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico


# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

show_excerpts: false

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  aicex:
    output: true
    permalink: /:collection/:path/
  aic2023:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      true
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-seo-tag
  - jemoji
